services:
  frontend:
    image: frontend:dev
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    env_file:
      - path: frontend/.env
        required: true
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /frontend/src

  backend:
    image: backend:dev
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - path: backend/.env
        required: true
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
