services:
    frontend:
        image: frontend:dev
        container_name: frontend
        build:
            context: frontend
            dockerfile: Dockerfile
            target: development
        ports:
            - "8080:8080"
        env_file:
            - path: frontend/.env
              required: true
        develop:
            watch:
                - action: sync
                  path: ./frontend/src
                  target: /frontend/src
                - action: sync
                  path: ./frontend/public
                  target: /frontend/public

    backend:
        image: backend:dev
        container_name: backend
        build:
            context: backend
            dockerfile: Dockerfile
            target: development
        ports:
            - "5000:5000"
        env_file:
            - path: backend/.env
              required: true
        develop:
            watch:
                - action: sync
                  path: ./backend/src
                  target: /backend/src
        networks:
            monitoring-network:
                ipv4_address: 172.16.238.11

    prometheus:
        image: prom/prometheus
        ports: 
        - "9090:9090"
        volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            monitoring-network:
                ipv4_address: 172.16.238.12

    test:
        profiles:
            - test
        image: backend:test
        build:
            context: backend
            dockerfile: Dockerfile
            target: test
        env_file:
            - path: backend/.env.test
              required: true

networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24