services:
    frontend:
        image: frontend:dev
        build:
            context: frontend
            dockerfile: Dockerfile
            target: development
        ports:
            - "1234:1234"
        env_file:
            - path: frontend/.env
              required: true
        develop:
            watch:
                - action: sync
                  path: ./frontend/src
                  target: /frontend/src

    backend:
        image: backend:dev
        build:
            context: backend
            dockerfile: Dockerfile
            target: development
        ports:
            - "5000:5000"
        env_file:
            - path: backend/.env
              required: true
        # entrypoint: /bin/bash
        # stdin_open: true # docker run -i
        # tty: true
        develop:
            watch:
                - action: sync
                  path: ./backend/src
                  target: /backend/src

    test:
        profiles:
            - test
        image: backend:test
        build:
            context: backend
            dockerfile: Dockerfile
            target: test
        env_file:
            - path: backend/.env.test
              required: true
