[tool.poetry]
name = "playlist-manager"
version = "0.1.0"
description = ""
authors = ["CalPin <calum.pinder@softwire.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.0"
python-dotenv = "^1.0.0"
flask-cors = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
