- name: Update web servers
  hosts: managed-nodes
  remote_user: ec2-user
  tasks:
    - name: Install Git
      yum:
        name: "git"
        state: "present"
        update_cache: yes
      become: yes # Installing git must be run as the root user

    - name: Install Python
      yum:
        name: "python3.11"
        state: "present"
        update_cache: yes
      become: yes # Installing python must be run as the root user

    - name: Install Node
      yum:
        name: "nodejs"
        state: "present"
        update_cache: yes
      become: yes # Installing node must be run as the root user

    - name: Install Poetry
      shell:
        cmd: "curl -sSL https://install.python-poetry.org | python3.11 -"
        creates: "/home/ec2-user/.local/bin/poetry"

    - name: Create folder for Playlist Manager
      file:
        path: /opt/playlist-manager
        state: directory
        owner: "ec2-user"
      become: yes

    - name: Clone Playlist Manager
      git:
        repo: "https://github.com/CalPinSW/playlist-manager.git"
        version: "add-ansible-configuration"
        dest: "/opt/playlist-manager"

    - name: Use most recent Python version for Poetry
      shell:
        cmd: "poetry env use python3.11"
        chdir: "/opt/playlist-manager/backend"

    - name: Install Project Dependencies
      shell:
        chdir: "/opt/playlist-manager"
        cmd: ". ./install.sh"
