name: Snyk Security Scan
on: "push"
jobs:
    scan:
          name: scan
          runs-on: ubuntu-latest
          steps:
              - name: Checkout Repository
                uses: actions/checkout@v4
              - run: npm install
                working-directory: playlist-manager-next
              - uses: snyk/actions/setup@master
              - name: Snyk monitor
                working-directory: playlist-manager-next
                run: snyk test --severity-threshold=medium
                env:
                    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}